# Site settings
name: NightPxy 
email: 38695281@qq.com
author: NightPxy
url: https://github.com/NightPxy/
resume_site: https://nightpxy.github.io
github: https://github.com/NightPxy/
baseurl: ""
description: 个人技术博客
meta_description: NightPxy
motto: NightPxy 个人技术博客
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: luoyan35714

# Build settings
markdown: kramdown

baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9

